joints = {
    0: ["nose", "", "black", False],
    1: ["eye", "left", "green", True],
    2: ["eye", "right", "red", True],
    3: ["ear", "left", "green", True],
    4: ["ear", "right", "red", True],
    5: ["shoulder", "left", "green", False],
    6: ["shoulder", "right", "red", False],
    7: ["elbow", "left", "green", False],
    8: ["elbow", "right", "red", False],
    9: ["wrist", "left", "green", False],
    10: ["wrist", "right", "red", False],
    11: ["hip", "left", "green", False],
    12: ["hip", "right", "red", False],
    13: ["knee", "left", "green", False],
    14: ["knee", "right", "red", False],
    15: ["foot", "left", "green", False],
    16: ["foot", "right", "red", False],
}

links = {
    0: ["right ear to right eye", (4, 2), "", False],
    1: ["right eye to nose", (2, 0), "", False],
    2: ["nose to left eye", (0, 1), "", False],
    3: ["left eye to left ear", (1, 3), "", False],
    4: ["left shoulder to right shoulder", (5, 6), "chest line", True],
    5: ["right elbow to right shoulder", (6, 8), "right arm", True],
    6: ["right elbow to right wrist", (8, 10), "right forearm", True],
    7: ["left shoulder to left elbow", (5, 7), "left arm", True],
    8: ["left elbow to left wrist", (7, 9), "left forearm", True],
    9: ["right shoulder to right hip", (6, 12), "suspender right", True],
    10: ["left shoulder to left hip", (5, 11), "suspender left", True],
    11: ["left hip to right hip", (11, 12), "belt", True],
    12: ["right hip to right knee", (12, 14), "right thigh", True],
    13: ["right knee to right foot", (14, 16), "right calf", True],
    14: ["left hip to left knee", (11, 13), "left thigh", True],
    15: ["left knee to left foot", (13, 15), "left calf", True],
    16: ["nose to left shoulder", (0, 5), "nose left", True],
    17: ["nose to right shoulder", (0, 6), "nose right", True],
}